# Data

```{r}
library(dplyr)
library(ggplot2)
data <- read.csv("./StudentsPerformance.csv", stringsAsFactors = FALSE)
students <- head(data, 30)
str(students)

low_income <- head(dplyr::filter(data, lunch == "free/reduced"), 30)
high_income <- head(dplyr::filter(data, lunch == "standard"), 30)
```

# Averages

```{r}
math_average <- mean(students$math.score, na.rm = TRUE)
reading_average <- mean(students$reading.score, na.rm = TRUE)
writing_average <- mean(students$writing.score, na.rm = TRUE)
math_average
reading_average
writing_average
low_income_math_average <- mean(low_income$math.score, na.rm = TRUE)
low_income_reading_average <- mean(low_income$reading.score, na.rm = TRUE)
low_income_writing_average <- mean(low_income$writing.score, na.rm = TRUE)
low_income_math_average
low_income_reading_average
low_income_writing_average
high_income_math_average <- mean(high_income$math.score, na.rm = TRUE)
high_income_reading_average <- mean(high_income$reading.score, na.rm = TRUE)
high_income_writing_average <- mean(high_income$writing.score, na.rm = TRUE)
high_income_math_average
high_income_reading_average
high_income_writing_average
```

# Standard Deviations

```{r}
math_std    <- sd(students$math.score, na.rm = TRUE)
reading_std <- sd(students$reading.score, na.rm = TRUE)
writing_std <- sd(students$writing.score, na.rm = TRUE)
math_std
reading_std
writing_std
low_income_math_std    <- sd(low_income$math.score, na.rm = TRUE)
low_income_reading_std <- sd(low_income$reading.score, na.rm = TRUE)
low_income_writing_std <- sd(low_income$writing.score, na.rm = TRUE)
low_income_math_std
low_income_reading_std
low_income_writing_std
high_income_math_average <- sd(high_income$math.score, na.rm = TRUE)
high_income_reading_average <- sd(high_income$reading.score, na.rm = TRUE)
high_income_writing_average <- sd(high_income$writing.score, na.rm = TRUE)
high_income_math_average
high_income_reading_average
high_income_writing_average
```

# Plots

## Box Plot

```{r}

math_lunch_box <- ggplot(students, aes(x=lunch, y=math.score)) + geom_boxplot(fill = c(rep("lightcoral",1), rep("lightblue",1))) +
    scale_x_discrete(labels=c("Low Income","High Income"))
math_lunch_box+ labs(x = "Income Level", y = "Math Score" , title = "Math Score by Income Level")


reading_lunch_box <- ggplot(students, aes(x=lunch, y=reading.score)) + geom_boxplot(fill = c(rep("lightcoral",1), rep("lightblue",1))) +
    scale_x_discrete(labels=c("Low Income","High Income"))
reading_lunch_box + labs(x = "Income Level", y = "Reading Score" , title = "Reading Score by Income Level")

writing_lunch_box <- ggplot(students, aes(x=lunch, y=writing.score)) + geom_boxplot(fill = c(rep("lightcoral",1), rep("lightblue",1))) +
    scale_x_discrete(labels=c("Low Income","High Income"))
writing_lunch_box + labs(x = "Income Level", y = "Writing Score", title = "Writing Score by Income Level")

```

## Histograms
```{r}

reduced_math_hist <- ggplot(low_income, aes(x=math.score)) + geom_histogram(fill = rep("lightcoral"))
reduced_math_hist + labs(x = "Math Score", y = "Number of Students" , title = "Math Scores Across Low Income Students")

reduced_reading_hist <- ggplot(low_income, aes(x=reading.score)) + geom_histogram(fill = rep("lightcoral"))
reduced_reading_hist + labs(x = "Reading Score", y = "Number of Students" , title = "Reading Scores Across Low Income Students")

reduced_writing_hist <- ggplot(low_income, aes(x=writing.score)) + geom_histogram(fill = rep("lightcoral"))
reduced_writing_hist + labs(x = "Writing Score", y = "Number of Students" , title = "Writing Scores Across Low Income Students")

high_math_hist <- ggplot(high_income, aes(x=math.score)) + geom_histogram(fill = rep("lightblue"))
high_math_hist + labs(x = "Math Score", y = "Number of Students" , title = "Math Scores Across High Income Students")

high_reading_hist <- ggplot(high_income, aes(x=reading.score)) + geom_histogram(fill = rep("lightblue"))
high_reading_hist + labs(x = "Reading Score", y = "Number of Students" , title = "Reading Scores Across High Income Students")

high_writing_hist <- ggplot(high_income, aes(x=writing.score)) + geom_histogram(fill = rep("lightblue"))
high_writing_hist + labs(x = "Writing Score", y = "Number of Students", title = "Writing Score Across High Income Students")


```

# Correlation and Confidence Interval
```{r}
# degrees of freedom for sample mean is 29
# significance value is 0.05
# We need a critical t value
t_critical<- qt(p=.975, df=29)
margin_math <- t_critical*math_std/sqrt(30)
margin_reading <- t_critical*reading_std/sqrt(30)
margin_writing <- t_critical*writing_std/sqrt(30)
lower_interval_math <- math_average - margin_math
higher_interval_math <- math_average + margin_math
lower_interval_reading <- reading_average - margin_reading
higher_interval_reading <- reading_average + margin_reading
lower_interval_writing <- writing_average - margin_writing
higher_interval_weriting <- writing_average + margin_writing
#Values above denote 95% confidence interval from [low to high]

low_income_math <-low_income[["math.score"]]
high_income_math <-high_income[["math.score"]]

math_correlation_dataframe <- data.frame( 
                group = rep(c("low", "high"), each = 30),
                weight = c(low_income_math,  high_income_math)
                )
res_math <- t.test(low_income_math, high_income_math, paired = TRUE)
res_math

low_income_reading <-low_income[["reading.score"]]
high_income_reading <-high_income[["reading.score"]]

math_correlation_dataframe <- data.frame( 
                group = rep(c("low", "high"), each = 30),
                weight = c(low_income_reading,  high_income_reading)
                )
res_reading <- t.test(low_income_reading, high_income_reading, paired = TRUE)
res_reading

low_income_writing <-low_income[["writing.score"]]
high_income_writing <-high_income[["writing.score"]]

math_correlation_dataframe <- data.frame( 
                group = rep(c("low", "high"), each = 30),
                weight = c(low_income_writing,  high_income_writing)
                )
res_writing <- t.test(low_income_writing, high_income_writing, paired = TRUE)
res_writing
```


